name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Deploy to Digitalocean
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SGB_SSH_HOST }}
          user: root
          key: ${{ secrets.SGB_SSH_USER}}
          command: |
            cd /home/sgb/react/chat-react
            git reset --hard
            git pull https://github.com/yassinebebba/chat-react.git master
            npm install
            npm run build
            pm2 delete chat-react
            pm2 serve --spa --port 3000 build/ --name chat-react
            echo "Successfully deployed to Digitalocean"

